### ISSUE TITLE
Modification Response Form - Aesthetic Layout & Formatting Updates

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#133]
Please implement the following updates as requested by stakeholders:
1. Update the title of the form to "Modification Response Page"
2. Enlarge the vertical spacing of the input text box associated with the "Modification Response Text" to roughly twice its existing vertical size.
3. Re-order the Agency Checkboxes (located within the Package Approver section) so that all checkboxes are listed within a single column.
4. Update the text labels for each of the Agency Checkboxes (located within the Package Approver section) to display the full names for each - reference the text within the graphic below.
5. Update the text labels for each of the Request Approver Agency Dropdowns (located within the Request Approver section) to display abbreviated names for each - reference the text within the graphic below.

![image](https://cloud.githubusercontent.com/assets/4098544/6357488/e0a31e42-bc32-11e4-9c81-63c0bd07fb76.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
**Package Approver Section:**
1. list checkboxes in one single column vertically
2. re-order the checkboxes using the order displayed in the graphic below
3. increase the vertical space of *Package Approver* section as needed to accomodate these changes
4. ![image](https://cloud.githubusercontent.com/assets/4098544/6419298/f3535f30-be89-11e4-90cd-29cd50220a88.png)

**Request Approver Section:**
1. Update the text labels to use the abbreviations instead of the existing text for each. reference the graphic below
2. re-order the labels & checkboxes using the order displayed in the graphic below
3. ![image](https://cloud.githubusercontent.com/assets/4098544/6419501/cdfd5e82-be8b-11e4-883a-fa256c11aa95.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - Updated to Ready for Staging

**Comment by slmessier** [comment]
Please implement the following updates to the Modification Response Form that Tad has asked for within a subsequent iteration of requests:
1. **Add at least 1 line of entirely blank space above the “Original Request” user input field**
2. **Add at least 1 line of entirely blank space above the “Stakeholders who will be notified” user input field**
3. **Reorder the appearance of email recipient’s names to display <first Name> + <space character> + <Last name> (remove the comma character [,] )**
4. **Update text of ‘upload Request document ‘ label to “Upload Document”**
5. **Use a larger font for the “Sign” hyperlink for all instances within the form.**
6. **Update the notification checkbox area so that the vertical scroll bar remains visible at all times, without requiring the user to scroll horizontally to the right beforehand.**

![image](https://cloud.githubusercontent.com/assets/4098544/6871328/28ae43b2-d478-11e4-8559-ca4f1df9eff7.png)

**Comment by kanglu666** [comment]
done at KCI

**Comment by slmessier** [comment]
Item # 6 above still persists. Please truncate the character width of the strings within the Notification Menu box appropriately so that the vertical scrollbar always appears without scrolling horizontally.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
