### ISSUE TITLE
QA3 PDF Report - Correct Spelling Mistake: "Original"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#152]
**Please update the following spelling mistake to "Original"**
**Please implement this update in DEVELOPMENT AND STAGING**

![image](https://cloud.githubusercontent.com/assets/4098544/6619444/a141f06e-c8a0-11e4-98a0-7a41bd97cd74.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
I'm still seeing the incorrect spelling in both DEVELOPMENT and STAGING.

**Comment by kanglu666** [comment]
done at SHA Staging.

**Comment by slmessier** [comment]
validated successfully in STAGING. Update to Ready for Production.

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
