### ISSUE TITLE
MDE Toolkit - Update User Role to "Reviewer" - Application Error Message Issued

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#35]
The system issues the‘Application Error’ during the workflow to update user role to “reviewer” (using admin – update user)

![image](https://cloud.githubusercontent.com/assets/4098544/3443775/0329d022-0127-11e4-927f-a580de613f74.png)

After updating role to "reviewer, then clicking save":
![image](https://cloud.githubusercontent.com/assets/4098544/3443778/18e42868-0127-11e4-982f-bd9d07e43aa0.png)

**Comment by kanglu666** [comment]
fixed with #113 at KCI, please test

**Comment by slmessier** [comment]
this issue still persists when exclusively testing the function to update the system role within the MDE toolkit.

**Comment by slmessier** [comment]
this issue can be replicated only for user name - smessier. The cause of the error may likely have something to do with the configuration of that specific user account in particular - perhaps the assigned projects that have been associated to the user name.

**Comment by slmessier** [comment]
since this issue appears to be specific to an individual user name it can otherwise be considered as an exception for this specific case, and will be closed.
